### PR TITLE
Stylistic changes

### PR DESCRIPTION
**Pull request by erilyth**
A few style changes,

- Category label background color
- Team1,Tie,Team2 links converted to buttons
- Center align question and answer text
- Reduce page top margin

### CODE REVIEW

**Comment by erilyth** [comment]
I signed it!

**Comment by mina86** [comment]
I’m not happy with the ‘top: -3%’ though. Better way to reduce top margin is by adjusting H1’s styles.

**Comment by erilyth** [comment]
Reducing the margin to 0 on h1 fixed it

**Comment by mina86** [comment]
So my issue with this pull request is that it pulls whole bunch of third party CSS rules changing a lot of the appearance of the page. I’m not necessarily objecting to changed looks but I would rather the embedded CSS was modified rather then the page depending on Internet access. The worst part is the third party rules overwrite part of the embedded rules so it’s no longer clear what is happening and because of what reason.

**Comment by erilyth** [comment]
@mina86 I removed the external libraries and used normal buttons instead of the ripple buttons.

**Comment by mina86** [comment]
Thanks. Applied.

**Pull request closed without merging**
